config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'welcome#index'
  resources 'adminviews' #crud de los usuarios
  resources 'products'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_attached_file :avatar, styles: { small: "100x100", medium: "500x500", thumb: "800x800" }, default_url: "/assets/default-avatar.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  validates_attachment :avatar,
  content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

  
end

app/controllers/adminviews_controller.rb
class AdminviewsController < ApplicationController
   def index
   	  @users = User.all
   end
   def show
   	   @user = User.find(params[:id])
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
   def index
   	
   end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private
  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
  def account_update_params
    params.require(:user).permit(:name, :age, :avatar, :level_permission, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/adminviews/index.html.erb
<% @users.inspect %>
<div class="container">
<h3>Revisa los usuarios creados</h3>
	<table class="table table-stripper table-hover">
		<thead>
			<tr>
			    <th></th>
				<th>Nombre</th>
				<th>Apellido</th>
				<th>Edad</th>
				<th>Email</th>
				<th>Permisos</th>
			</tr>
		</thead>
		<tbody>
		<% @users.each do |user| %>
		  <tr>
		    <td><%= link_to(image_tag(user.avatar.url(:small), class:'img-responsive'), edit_user_registration_path(:id), class:'img-avatar')%></td>
		    <td><%= user.name %></td>
		    <td><%= user.last_name %></td>
		    <td><%= user.age %></td>
		    <td><%= user.email %></td>
		  	<td><%= user.level_permission %></td>	
		 </tr>
		<%end%>
		</tbody>	
	</table>
</div>

app/views/adminviews/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @user.name %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @user.last_name %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Galerias</title>
  <link href="https://fonts.googleapis.com/css?family=Hind:300,400,500,600,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'partials/header'%>
<div class="container float-special">	
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
</div>

<%= yield %>

</body>
</html>

app/views/partials/_header.html.erb
<nav class="navbar navbar-inverse nav-style-gale">
  <div class="collapse navbar-collapse submenu" id="Navbar2">
  <div class="container">
   <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
            <% if current_user.level_permission === 3 %> <!--si User admin -->
                <li>
                  <%= link_to 'ver usuarios registrados',adminviews_path %>
                </li>
            <%end%>
            <li class="avatar-logeado">
             <%= link_to(image_tag(current_user.avatar.url(:small), class:'img-responsive'), edit_user_registration_path, class:'img-avatar')%>
            </li> 
            <li class="name-user-align">
            <span>Bienvenido: </span>
              <% if current_user.name === "" %><!--si nombre vacio -->
                Actualiza tus datos
               <%else%>
               <%= current_user.name %>
              <%end%>
            </li>
            <li>
               <%= link_to('Editar Perfil', edit_user_registration_path) %>
            </li>
            <li>
            <%= link_to('Cerrar sesión', destroy_user_session_path, :method => :delete) %>        
            </li>
          <% else %>
            <li>
              <%= link_to('Regístrate', new_user_registration_path)  %>
            </li>
            <li>
            <%= link_to('Ingresa', new_user_session_path)  %>  
            </li>
      <% end %>
      </ul>
      </div>
</div>
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
      <a class="navbar-brand" href="#">Nombre del sitio</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">

      <ul class="nav navbar-nav navbar-right">
        <li class="active"><%= link_to "Home", root_path, class:'go'%></li>
        <li><%= link_to "Home", root_path, class:'go'%></li>
        <li><%= link_to "Home", root_path, class:'go'%></li>
        
      </ul>
    
    </div>

  </div>

</nav>

app/views/products/index.html.erb
Hola producto

app/views/welcome/index.html.erb
<%= link_to "Change your password", edit_user_registration_path %>